/**
 * Publishes the data contract for the Django developer.
 *
 * The zod schemas in src/lib/data/schemas.ts are the single source of truth;
 * this turns them into JSON Schema (docs/api-contract/*.json) and a readable
 * endpoint reference (docs/API-CONTRACT.md). Run it whenever a schema changes:
 *
 *   pnpm contract:export
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import * as S from "../src/lib/data/schemas.ts";

const OUT_DIR = fileURLToPath(new URL("../../../docs/api-contract/", import.meta.url));
const DOC = fileURLToPath(new URL("../../../docs/API-CONTRACT.md", import.meta.url));

/** Each endpoint, the schema of its response, and what it is for. */
const ENDPOINTS = [
  {
    method: "GET",
    path: "/settings",
    schema: "settings",
    type: S.settingsSchema,
    about: "Global chrome: nav, top bar, floating dock, contact modal fields, footer.",
  },
  {
    method: "GET",
    path: "/pages/home",
    schema: "home",
    type: S.homeSchema,
    about: "Every Home section in render order.",
  },
  {
    method: "GET",
    path: "/pages/about",
    schema: "about",
    type: S.aboutPageSchema,
    about: "About page: hero, about block, plans, vision/mission tabs, core values.",
  },
  {
    method: "GET",
    path: "/pages/offer",
    schema: "offer",
    type: S.offerSchema,
    about: "Offer page.",
  },
  {
    method: "GET",
    path: "/pages/book-now",
    schema: "book-now",
    type: S.bookNowSchema,
    about: "Book Now page, including the booking-form download link.",
  },
  {
    method: "GET",
    path: "/pages/contact",
    schema: "contact",
    type: S.contactPageSchema,
    about: "Contact page: form definition, map embed, hotline, info cards.",
  },
  {
    method: "GET",
    path: "/packages",
    schema: "packages",
    type: S.ownershipPackageSchema.array(),
    about: "All ownership packages. Drives generateStaticParams, so every slug here gets a page.",
  },
  {
    method: "GET",
    path: "/packages/{slug}",
    schema: "package",
    type: S.ownershipPackageSchema,
    about: "One package. 404 if the slug is unknown.",
  },
  {
    method: "GET",
    path: "/gallery",
    schema: "gallery",
    type: S.gallerySchema,
    about: "Gallery page: categories, the All set and the per-category sets.",
  },
  {
    method: "GET",
    path: "/events",
    schema: "events",
    type: S.eventsPageSchema,
    about: "Events list page, including the filter's category options.",
  },
  {
    method: "GET",
    path: "/events/filter",
    schema: "event-list",
    type: S.eventSummarySchema.array(),
    about: "Filtered events. See the query parameters below.",
    params: [
      ["start_date", "`d-m-Y`, e.g. `29-09-2026`. Optional."],
      ["end_date", "`d-m-Y`. Optional."],
      ["category_id", "Category id from `/events`. Empty means all."],
    ],
  },
  {
    method: "GET",
    path: "/events/{slug}",
    schema: "event",
    type: S.eventDetailSchema,
    about: "One event. 404 if unknown.",
  },
  {
    method: "GET",
    path: "/events/{slug}/related",
    schema: "event-list",
    type: S.eventSummarySchema.array(),
    about: "Other events to show under an event.",
  },
  {
    method: "GET",
    path: "/posts",
    schema: "posts",
    type: S.postsPageSchema,
    about: "Blog list page.",
  },
  {
    method: "GET",
    path: "/posts/{slug}",
    schema: "post",
    type: S.postDetailSchema,
    about: "One post, with its sidebar. 404 if unknown.",
  },
  {
    method: "POST",
    path: "/forms/contact",
    schema: "contact-form-payload",
    type: null,
    about: "Contact form submission. See the payload and error format below.",
  },
] as const;

await mkdir(OUT_DIR, { recursive: true });

const written: string[] = [];
const seen = new Set<string>();
for (const endpoint of ENDPOINTS) {
  if (!endpoint.type || seen.has(endpoint.schema)) continue;
  seen.add(endpoint.schema);
  const json = z.toJSONSchema(endpoint.type, { io: "output", unrepresentable: "any" });
  const file = `${endpoint.schema}.schema.json`;
  await writeFile(path.join(OUT_DIR, file), JSON.stringify(json, null, 2) + "\n");
  written.push(file);
}

const rows = ENDPOINTS.map((e) => {
  const schema = e.type
    ? `[\`${e.schema}.schema.json\`](api-contract/${e.schema}.schema.json)`
    : "—";
  return `| \`${e.method}\` | \`${e.path}\` | ${schema} | ${e.about} |`;
}).join("\n");

const filterParams = ENDPOINTS.find((e) => "params" in e && e.params)!;
const paramRows = (filterParams as { params: readonly (readonly [string, string])[] }).params
  .map(([name, desc]) => `| \`${name}\` | ${desc} |`)
  .join("\n");

const doc = `# API Contract — INDEX Eco Resort

> **Generated by \`pnpm contract:export\` from \`services/frontend/src/lib/data/schemas.ts\`.**
> Do not edit by hand; change the zod schemas and re-run.
> Last generated: ${new Date().toISOString().slice(0, 10)}

This is the handoff document for the backend. The Next.js frontend is finished
and self-contained: it currently renders a snapshot of the existing site. When a
backend implements the endpoints below, the frontend switches to it by setting
two environment variables — no code change.

## Ground rules

1. **The response shapes are fixed.** They were captured from the live site, and
   the frontend validates every response against the JSON Schemas in
   \`docs/api-contract/\`. A response that does not match fails loudly rather than
   rendering wrong content.
2. **Text is never normalised.** Typos, mixed Bangla/English and the known
   content mistakes listed in \`docs/01-SITE-AUDIT.md §9\` are real data. Fix them
   in the admin panel, not in the API.
3. **Links are verbatim.** \`href\` may be \`"#"\` or \`null\`; that is meaningful —
   it is what the current site does, and the frontend reproduces it exactly.
4. **Every current URL must still work.** The frontend routes \`/\`, \`/about-us\`,
   \`/{package-slug}\` (e.g. \`/gold-ownership-2\`), \`/offer\`, \`/book-now\`, \`/event\`,
   \`/events/{slug}\`, \`/blogs\`, \`/blog-details/{slug}\`, \`/gallery\` and \`/contact\`.
   Slugs come from the API, so they must match the existing ones.
5. **Media** may be absolute URLs or paths. Paths are resolved against
   \`MEDIA_BASE_URL\`. The current media is mirrored in
   \`services/frontend/public/media/\` with its original relative paths — that plus
   \`services/frontend/src/fixtures/*.json\` is the data to seed the database with.

## Endpoints

| Method | Path | Response schema | Purpose |
|---|---|---|---|
${rows}

### \`GET /events/filter\` query parameters

| Parameter | Value |
|---|---|
${paramRows}

Behaviour to preserve from the current site:

- Dates are **\`d-m-Y\`** (day-month-year, zero padded) — the format the existing
  date picker sends. Not ISO.
- If exactly one of \`start_date\`/\`end_date\` is given **and** \`category_id\` is
  empty, the filter is ignored and the full list is returned.
- An event with no dates never matches a date filter.
- An empty result is a \`200\` with an empty array, not a \`404\`.

## \`POST /forms/contact\`

Request body (\`application/json\`). Field names are exactly those the current
site submits:

| Field | Type | Notes |
|---|---|---|
| \`name\` | string | Required by the modal form, not by the contact page form. |
| \`phone\` | string | Same. The page form uses a numeric input. |
| \`email\` | string | Same. |
| \`address\` | string | The modal sends the literal string \`"N/A"\`; the page form sends the typed address. |
| \`message\` | string | Optional in both. |

Responses:

- \`200\` — accepted. The frontend then shows the site's existing success text,
  "✓ Message sent successfully!".
- \`422\` — validation failed, with field-level messages the frontend maps back
  onto the inputs:

\`\`\`json
{
  "errors": {
    "email": ["Enter a valid email address."],
    "phone": ["This field is required."]
  }
}
\`\`\`

- Any other status is reported to the visitor as a generic failure.

> There is **no comment endpoint**. The "Leave a Reply" block on event pages is
> decorative markup on the current site — no form, no handler, nothing stored —
> so the frontend does not render it. If comments are wanted, that is new scope.

## JSON Schemas

${written.map((f) => `- [\`${f}\`](api-contract/${f})`).join("\n")}

Generated with JSON Schema draft 2020-12.
`;

await writeFile(DOC, doc);
console.log(`docs/api-contract/: ${written.length} schemas`);
for (const f of written) console.log(`  ${f}`);
console.log(`docs/API-CONTRACT.md: ${ENDPOINTS.length} endpoints`);
